### ISSUE TITLE
Extend does not default to true

### ISSUE THREAD

**Issue by steakscience** [endigma/unocss-preset-radix#11]
Hi,

The docs say extend defaults to true. In the code, it defaults to false:

https://github.com/endigma/unocss-preset-radix/blob/b9d809f9737883f9c93df364a1f2c87d04dbe873/src/index.ts#L32-L36

**Comment by steakscience** [comment]
However, it looks like if you extend (ie extend = true), radix colors will not work

**Comment by endigma** [comment]
I don't know of a way to get rid of the default preset's colors, the use case for this was another user who wanted their own theme to be preserved I think. If this is important to you I can look back into modifying the object more surgically.

**Comment by steakscience** [comment]
Personally, I ended up manually adding radix colors into my own theme to avoid this issue.

Not sure either what the best solution is. I can close this issue.
