### ISSUE TITLE
Add foreground color

### ISSUE THREAD

**Issue by silveltman** [endigma/unocss-preset-radix#13]
Some radix scales use black on hue9, some use white. A selector for this would be great.

Just sharing my personal fix for this:
```
    theme: {
      colors: {
        foreground: 'var(--un-preset-theme-fg)',
        'foreground-base': getForeground(options.colors.base),
        'foreground-primary': getForeground(options.colors.primary),
        'foreground-secondary': getForeground(options.colors.secondary),
      },
    },
    rules: [
      [
        'hue-base',
        {
          '--un-preset-theme-fg': getForeground(options.colors.base),
        },
      ],
      [
        'hue-primary',
        {
          '--un-preset-theme-fg': getForeground(options.colors.primary),
        },
      ],
      [
        'hue-secondary',
        {
          '--un-preset-theme-fg': getForeground(options.colors.secondary),
        },
      ],
    ],
```

**Comment by endigma** [comment]
Yeah thats a pretty good idea, you mean to select between the dark fg and light fg colors? Something like `darkfg:fg-black lightfg:fg-white`?

**Comment by endigma** [comment]
I think there could potentially be some magic stuff here to allow an extra color to come with the hue 0-12 for fg, maybe even like `fg[1..12]` etc

**Comment by silveltman** [comment]
I don't think it would have to be difficult, it's only about this part of the docs:
![image](https://github.com/endigma/unocss-preset-radix/assets/52583398/10d08f7f-51ab-48e9-9eef-afc5a2c1fc5a)

The following classes would suffice:

-bluefg
-redfg 
Etc.

-huefg 

For sky-amber it would be black, for the other colors it would be white

**Comment by endigma** [comment]
I suppose 11 and 12 are universal foregrounds for lower numbered backgrounds, could just add another color to every palette for the appropriate high contrast foreground color. I'll look into it.

**Comment by silveltman** [comment]
Yes you're right, for the lower numbered backgrounds 11 and 12 are fine indeed.

You solution sounds fine 👌🏼

**Comment by endigma** [comment]
Added in 2.5.2
