### ISSUE TITLE
Plugin breaks regular colors theme settings

### ISSUE THREAD

**Issue by silveltman** [endigma/unocss-preset-radix#19]
When using this plugin the regular theme.colors does not work anymore.

The following does not work:
```
    theme: {
      colors: {
        hello: 'red',
      },
    },
```

When removing the plugin it works instantly

**Comment by endigma** [comment]
yep, there's some hacky stuff to remove colors added by mini, which conflict. you should write your custom colors into a preset and put it after this one.

**Comment by silveltman** [comment]
Good to know, thank you!

**Comment by endigma** [comment]
I don't think there's a way to not do this, but I'll look into it when I get around to a little overhaul I'd like to do.
