### ISSUE TITLE
Light/Dark Alpha and overlay colors are not included

### ISSUE THREAD

**Issue by thewebartisan7** [endigma/unocss-preset-radix#4]
I see that you are excluding alpha and overlay (whiteA/blackA) colors and some code are commented.

Is there a reasons why you didn't include them?

Can we add back? I can make PR.

**Comment by endigma** [comment]
Honestly I don't know what to use them for, and I planned to add proper unocss opacity support at some point. I'd accept a PR adding the alpha variants.

**Comment by thewebartisan7** [comment]
Thanks for quick reply. I will check into alpha variants in next days and open PR.

> Honestly I don't know what to use them for, and I planned to add proper unocss opacity support at some point.

I am not sure what are the benefits of using unocss opacity support instead of already created radix one? I am new to unocss so I am maybe missing the point.

Yes it's not common, but there is use case, for example could be for example an overlay background on some images so you can add some text or button on top of it.

I think it's better have it ready to be used since Radix provide it, rather than not having it when you need.

Can we also add the whiteA and blackA, as this are nice to be used with overlays such as modal, and they don't change with dark theme.

**Comment by thewebartisan7** [comment]
@endigma I open PR for this https://github.com/endigma/unocss-preset-radix/pull/5

Let me know your feedback.
