### ISSUE TITLE
Any plans to include alpha palette?

### ISSUE THREAD

**Issue by prodkt** [endigma/unocss-preset-radix#8]
Keep running into the issue of there not being alpha values included in this package. Is there any chance this is on your radar with plans to implement? If not, all good but would be very helpful to know so we can pivot. Thanks

**Comment by endigma** [comment]
There's actually a PR open for it, but it got caught up on some sort of typescript thing. See #5.

**Comment by r0nsha** [comment]
@endigma Hey, I needed alpha colors and overlay colors in my UI so I implemented it in my own fork. I don't know if this is what you want to happen, but I made it so alpha colors are added automatically according to your palette, and that `blackA` and `whiteA` are added to `:root` by default.

Here are the generated overlay colors:
![image](https://user-images.githubusercontent.com/44722426/235293417-7db871c1-a05e-4242-b155-63284f78a7f5.png)

And here's a small section of the generated alpha sections in my app:
![image](https://user-images.githubusercontent.com/44722426/235293468-505d3edf-dee9-4b32-80e7-58bbc72d18ba.png)

I'll also open a PR, let me know what you think :)

**Comment by prodkt** [comment]
Appreciate ya @endigma on the implementation!
